# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.

scrape_configs:
  - job_name: "opentelemetry"
    static_configs:
      - targets: ["localhost:9464"] # Endpoint of the Prometheus Exporter
